### ISSUE TITLE
Add upper case and title case support

### ISSUE THREAD

**Issue by kkaefer** [dropbox/miniutf#2]
Seems like the data already contains upper case and title case mappings?

**Comment by j4cbo** [comment]
Perhaps too late to be useful, but just for completeness...

We only implemented lowercase because that's all we had need for internally, and wanted to save on binary size as much as possible. Adding upper/titlecase as a config option (`#define` maybe?) would be an option, but leaving them out was intentional.

**Comment by kkaefer** [comment]
For reference, we switched to https://bitbucket.org/alekseyt/nunicode
